---
- name: Check for docker in /run
  stat:
    path: /run/docker
  register: p

- name: Install Docker
  shell:
    cmd: "curl -sSL https://get.docker.com | sh"
  when: not p.stat.exists

- name: Add the user 'pi' with a bash shell, appending the group 'docker' to the user's groups
  user:
    name: pi
    shell: /bin/bash
    groups: 
    - docker
    append: yes

- name: install libffi-dev libssl-dev
  apt:
    name: [ "libffi-dev", "libssl-dev" ]
    install_recommends: yes

- name: install python3
  apt:
    name: [ "python3","python3-pip" ]
    install_recommends: yes

- name: install python-configparser
  apt:
    name: [ "python-configparser" ]
    state: absent

- name: Install docker-compose
  shell:
    cmd: "pip3 -v install docker-compose"    

- name: systemctl enable docker
  shell:
    cmd: "systemctl enable docker"    
    
- name: create /var/docker-compose
  file:
    path: "{{  item }}"
    recurse: yes
    mode: 0755
    #owner: postgres
    owner: pi
    group: pi
  with_items:         
    - "/var/docker-compose/data/portainer"    

- name: 'prepare default daemon configuration'
  copy:
    src: 'daemon.json'
    dest: '/etc/docker/daemon.json'

- name: remove /var/docker-compose/prometheus
  ansible.builtin.file:
    path: /var/docker-compose/prometheus
    state: absent  