--- 
- name: create /var/docker-compose/fragments
  file:
    path: "{{  item }}"
    recurse: yes
    mode: 0755
    owner: pi
    group: pi
  with_items:         
    - "/var/docker-compose/fragments"

- name: Create Docker files from template
  template:
    src: "docker-compose.yaml.j2"
    dest: "/var/docker-compose/fragments/docker-compose-motioneye.yaml"
    mode: 0755
    owner: pi
    group: pi

