---
- name: Add a line to a file if the file does not exist, without passing regexp
  ansible.builtin.lineinfile:
    path: /boot/config.txt
    line: "{{ item }}"
    create: yes
  with_item:
  - start_x=1             # essential
  - gpu_mem=128           # at least, or maybe more if you wish
  - disable_camera_led=0  # optional, if you don't want the led to glow
